### PR TITLE
Add Google Drive backend instead of local text files

### PR DESCRIPTION
**Pull request by markfullmer**
This branch demonstrates switching to a Google Drive backend. Any files placed in https://drive.google.com/drive/folders/0BxeFmOHdUjWRbHBqM1kzLU9ES1k will automatically be discovered by the code and displayed as options. 

The new "Texts" allows for setting what mime type should be returned. It defaults to "text/html" to preserve formatting created in Drive, but if this proves problematic, passing "text/plain" as the second parameter to getText() will return plain text.

### CODE REVIEW

**Comment by markfullmer** [comment]
FYI @esparkhu . You should have access to https://drive.google.com/drive/folders/0BxeFmOHdUjWRbHBqM1kzLU9ES1k

**Comment by esparkhu** [comment]
A crap. I spent a long time fixing Conan and the Phantom Avenger to all the (herd) and (hisd) on the local text file and now it is all gone!  I don't suppose there is a way to retrieve those two files that I worked on last night? 

    On Saturday, June 17, 2017 5:10 PM, Mark Fullmer <notifications@github.com> wrote:
 

 FYI @esparkhu . You should have access to https://drive.google.com/drive/folders/0BxeFmOHdUjWRbHBqM1kzLU9ES1k—

**Comment by markfullmer** [comment]
@esparkhu , do you mean these changes:

https://github.com/markfullmer/gendered_text/pull/9/files

https://github.com/markfullmer/gendered_text/pull/8/files 

Anything you push to Github will be retrievable in some form or another. The versions that I moved into Google Drive were the ones that were deployed currently in the "master" branch, but I or you can copy-paste the stuff from above into the Drive equivalents. Unless there is other work than that you're referring to?

**Comment by markfullmer** [comment]
@esparkhu , I'm planning to move the word map also into Google Drive. Between the two versions, https://docs.google.com/spreadsheets/d/1ask-U3chahOjLpBtJvUU0EIjKUi1cjB1U1dgbQ-nE9c/edit#gid=0 (Legacy style) and https://docs.google.com/spreadsheets/d/1-GUMdQ8iMpOUSz8PddPFZgf0YZZnPkAqPp8tuS5kMfI/edit#gid=0 do you have a structure preference?

To me, the latter, which has more columns but fewer rows, seems more humanly navigable, and reduces some duplication of the "pos" values.

**Comment by esparkhu** [comment]
Phew, thanks.  Yes, I can take the text I updated from the github pulled files and move them to the google doc. I added some words to the word map too, like aunt/uncle, I'll try to retrieve them from the github branch file. Overall, I like using Googles docs. It also makes adding stories and replacement words to the project much more user friendly.
I agree that the replacement word map is more navigable. https://docs.google.com/spreadsheets/d/1-GUMdQ8iMpOUSz8PddPFZgf0YZZnPkAqPp8tuS5kMfI/edit#gid=0 I also like seeing the 'display if different from determiner' column; it helps remind me of the herd and hisd uses. Let me know once you've finalized the word map file and I'll start adding to it.




 

    On Sunday, June 18, 2017 8:34 AM, Mark Fullmer <notifications@github.com> wrote:
 

 @esparkhu , I'm planning to move the word map also into Google Drive. Between the two versions, https://docs.google.com/spreadsheets/d/1ask-U3chahOjLpBtJvUU0EIjKUi1cjB1U1dgbQ-nE9c/edit#gid=0 (Legacy style) and https://docs.google.com/spreadsheets/d/1-GUMdQ8iMpOUSz8PddPFZgf0YZZnPkAqPp8tuS5kMfI/edit#gid=0 do you have a structure preference?To me, the latter, which has more columns but fewer rows, seems more humanly navigable, and reduces some duplication of the "pos" values.—

**Comment by markfullmer** [comment]
Okay, @esparkhu , the WordMap in the Google Drive folder is hooked up. Have at making edits there! If things somehow get out of whack, I've added a "Backup of Replacement Map" sheet to the folder, too, for reference.

**Pull request merged**
