### PR TITLE
Alice in Wonderland text

### PR DESCRIPTION
**Pull request by markfullmer**

### CODE REVIEW

**Comment by markfullmer** [comment]
Hey @esparkhu , this text was almost perfectly parameterized! (Impressive, given you don't yet have a good way to test it on the fly. I just noted one instance where the double curly braces were missing

> next peeped out, the Fish-{footman(Frog)}} was gone

The other thing -- and I should think about how to make this less cumbersome -- is that right now the legend *must* have names for all character variants. So, the proper legend for this text looks like this:

```
[[Alice/Alan/Alyx:female][Sibling/Sibling/Sibling:female][David/Dinah/Dana:female][Rabbit/Rabbit/Rabbit:male][Duke/Duchess/Regent:female][Pat/Pat/Pat:male][Bill/Bonnie/Bobbie:male][Caterpillar/Caterpillar/Caterpillar:male][Fish/Fish/Fish:male][King/Queen/Sovereign:female][cook/cook/cook:female][Hatter/Hatter/Hatter:male][King/Queen/Ruler:male]]
```

**Comment by markfullmer** [comment]
Oh, and one more thing, @esparkhu , it looks like some of the pronouns are not entered quite right. When I render the text as "Alan in Wonderland," I get:

> Alan was beginning to get very tired of sitting by him sister on the bank,

This should be entered as (i.e., "her" *determiner*)
`{{Alice}} was beginning to get very tired of sitting by {{ herd(Alice) }}`

**Comment by markfullmer** [comment]
Resolved via https://github.com/markfullmer/gendered_text/commit/522668abcf65ae0b00bfc27125564ea22e5c090f

**Comment by esparkhu** [comment]
Excellent! I"m going to read through the texts that are already up and try to catch mistakes.  
I'm noticing a problem with "dear" that comes up often unrelated to gender, for example at the opening of a letter. Also, your explanation about the placeholders makes sense. I keep finding more of them and may adjust previously defined ones. 
One question, what do we do about "Mrs."? The masculine "Mr." overlaps with "Ms." Can both Mrs and Ms use Mr as the male title?
I'm working on Frankenstein now and will do The White Company, by Sir Arthur Conan Doyle next. It is kind of fun to read through all these old stories. 
-Emily
 

    On Friday, June 16, 2017 12:15 PM, Mark Fullmer <notifications@github.com> wrote:
 

 Hey @esparkhu , this text was almost perfectly parameterized! (Impressive, given you don't yet have a good way to test it on the fly. I just noted one instance where the double curly braces were missing
next peeped out, the Fish-{footman(Frog)}} was gone
The other thing -- and I should think about how to make this less cumbersome -- is that right now the legend must have names for all character variants. So, the proper legend for this text looks like this:[[Alice/Alan/Alyx:female][Sibling/Sibling/Sibling:female][David/Dinah/Dana:female][Rabbit/Rabbit/Rabbit:male][Duke/Duchess/Regent:female][Pat/Pat/Pat:male][Bill/Bonnie/Bobbie:male][Caterpillar/Caterpillar/Caterpillar:male][Fish/Fish/Fish:male][King/Queen/Sovereign:female][cook/cook/cook:female][Hatter/Hatter/Hatter:male][King/Queen/Ruler:male]]

**Comment by esparkhu** [comment]
Yeah, I'm having a tough time with the determiner pronouns. The callouts are confusing.
What about - "That cup is {{hisd (Alice)}}" and "That cup is {{hers(Alice)}}" Are these two texts equivalent as far as output? 
or "The cat sat by {{herd(Alice)}} sister," and "The cat sat by {{his(Alice)}} sister." Would those function the same? 

    On Friday, June 16, 2017 12:18 PM, Mark Fullmer <notifications@github.com> wrote:
 

 Oh, and one more thing, @esparkhu , it looks like some of the pronouns are not entered quite right. When I render the text as "Alan in Wonderland," I get:
Alan was beginning to get very tired of sitting by him sister on the bank,
This should be entered as (i.e., "her" determiner)
{{Alice}} was beginning to get very tired of sitting by {{ herd(Alice) }}—

**Pull request closed without merging**
